//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManagement.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHangHoa()
        {
            this.tblChiTietHoaDonBanHangs = new HashSet<tblChiTietHoaDonBanHang>();
            this.tblChiTietHoaDonNhapHangs = new HashSet<tblChiTietHoaDonNhapHang>();
        }
    
        public string MaHangHoa { get; set; }
        public string MaLoaiHangHoa { get; set; }
        public string TenHangHoa { get; set; }
        public int SoLuong { get; set; }
        public string MaNhaCungCap { get; set; }
        public string MaNhaSanXuat { get; set; }
        public double GiaNhap { get; set; }
        public double GiaBan { get; set; }
        public string MoTa { get; set; }
        public byte[] HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHoaDonBanHang> tblChiTietHoaDonBanHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHoaDonNhapHang> tblChiTietHoaDonNhapHangs { get; set; }
        public virtual tblLoaiHangHoa tblLoaiHangHoa { get; set; }
        public virtual tblNhaCungCap tblNhaCungCap { get; set; }
        public virtual tblNhaSanXuat tblNhaSanXuat { get; set; }
    }
}
