//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManagement.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDonNhapHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHoaDonNhapHang()
        {
            this.tblChiTietHoaDonNhapHangs = new HashSet<tblChiTietHoaDonNhapHang>();
        }
    
        public string MaHoaDonNhap { get; set; }
        public string MaNhaCungCap { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<double> SoTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHoaDonNhapHang> tblChiTietHoaDonNhapHangs { get; set; }
        public virtual tblNhaCungCap tblNhaCungCap { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
