//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDonNhapHang
    {
        public string MaHoaDonNhap { get; set; }
        public string MaNhaCungCap { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<double> SoTien { get; set; }
    
        public virtual tblChiTietHoaDonNhapHang tblChiTietHoaDonNhapHang { get; set; }
        public virtual tblNhaCungCap tblNhaCungCap { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
